package dao.implement;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import dao.SummaryOSReportDao;
import entities.InputDateRunningDetail;
import entities.SummaryOSReportDetail;
import model.BeanCreateModel;
import th.in.totemplate.core.sql.Database;

public class SummaryOSReportDaoImpl implements SummaryOSReportDao {
	private BeanCreateModel bcModel = new BeanCreateModel();
	private Database database;
	private String message;

	// ------------------------------------------------------------------------------------------------
	public SimpleDateFormat sdf2 = new SimpleDateFormat("dd/MM/yyyy");
	public SimpleDateFormat sdfFull = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss.SSS");
	public SimpleDateFormat hhmm = new SimpleDateFormat("HH:mm");

	@SuppressWarnings("unused")
	private String conType;

	public SummaryOSReportDaoImpl(Database database2, String conType) {
		this.database = database2;
		this.message = "";
		this.conType = conType;
	}

	public String getMessage() {
		return this.message;
	}

	@Override
	public ArrayList<SummaryOSReportDetail> getSummaryOSReportDetail(ArrayList<InputDateRunningDetail> poList) {
		ArrayList<SummaryOSReportDetail> list = null;
		InputDateRunningDetail bean = poList.get(0);
		String MMyyyy = bean.getDate();
		String where = "";
		if ( ! where.equals("")) {
			where = " where " + where;
		}
		String begin = "01/" + MMyyyy;
		String declarePlan = ""
				+ " declare @BeginDateFirst date  = convert(date, '"
				+ begin
				+ "', 103) ;\r\n"
				+ " declare @today date  = cast(GETDATE() as date) ;\r\n";
		String sql = ""
//				+ " declare @BeginDateFirst date  = convert(date, '01/11/2023', 103) ;\r\n"
//				+ " declare @today date  = cast(GETDATE() as date) ; \r\n"
				+ declarePlan
				+ " declare @BeginDateZero date  = dateadd(month,-1,@BeginDateFirst) ;\r\n"
				+ " declare @BeginDateSecond date  = dateadd(month,1,@BeginDateFirst) ;\r\n"
				+ " declare @BeginDateThird date = dateadd(month,1,@BeginDateSecond) ; \r\n"
//				+ " declare @StockDateFirst varchar(2) = '26'; \r\n"
//				+ " declare @StockDateLast varchar(2) = '25' ; \r\n"
				+ " declare @StockDateFirst varchar(2) = CAST ( "
				+ "                                      ( SELECT [DayOfMonth] + 1 FROM [PPMM].[dbo].[StockDefaultDate] where [DataStatus] ='O' )"
				+ "                                       AS VARCHAR(2)"
				+ "                                      ); \r\n"
				+ " declare @StockDateLast varchar(2) = CAST ( "
				+ "										( SELECT [DayOfMonth] FROM [PPMM].[dbo].[StockDefaultDate] where [DataStatus] ='O' )"
				+ "										 AS VARCHAR(2)"
				+ "										) ; \r\n"
				+ " declare @FirstYear varchar(4)  = year( dateadd(YEAR,-1,@BeginDateFirst))   ;\r\n"
				+ " declare @LastYear varchar(4)  = year( dateadd(YEAR,1,@BeginDateFirst))  ; \r\n"
				+ " declare @BeginFirstMonth date  = datefromparts(\r\n"
				+ "			CAST( year(@BeginDateZero) as varchar(4))\r\n"
				+ "			,RIGHT('00' + cast(month(@BeginDateZero) as varchar(2)),2)\r\n"
				+ "		 ,@StockDateFirst\r\n"
				+ "		 ) ; \r\n"
				+ " declare @LastFirstMonth date  = datefromparts(\r\n"
				+ "			CAST( year(@BeginDateFirst) as varchar(4))\r\n"
				+ "			,RIGHT('00' + cast(month(@BeginDateFirst) as varchar(2)),2)\r\n"
				+ "		 ,@StockDateLast\r\n"
				+ "		 )  ; \r\n"
				+ " declare @BeginSecondMonth date  = datefromparts(\r\n"
				+ "			CAST( year(@BeginDateFirst) as varchar(4))\r\n"
				+ "			,RIGHT('00' + cast(month(@BeginDateFirst) as varchar(2)),2)\r\n"
				+ "		 ,@StockDateFirst\r\n"
				+ "		 )   ;\r\n"
				+ " declare @LastSecondMonth date  = datefromparts(\r\n"
				+ "			CAST( year(@BeginDateSecond) as varchar(4))\r\n"
				+ "			,RIGHT('00' + cast(month(@BeginDateSecond) as varchar(2)),2)\r\n"
				+ "		 ,@StockDateLast\r\n"
				+ "		 )  ;\r\n"
				+ " declare @BeginThirdMonth date  = datefromparts(\r\n"
				+ "			CAST( year(@BeginDateSecond) as varchar(4))\r\n"
				+ "			,RIGHT('00' + cast(month(@BeginDateSecond) as varchar(2)),2)\r\n"
				+ "		 ,@StockDateFirst\r\n"
				+ "		 ) ;\r\n"
				+ " declare @LastThirdMonth date  = datefromparts(\r\n"
				+ "			CAST( year(@BeginDateThird) as varchar(4))\r\n"
				+ "			,RIGHT('00' + cast(month(@BeginDateThird) as varchar(2)),2)\r\n"
				+ "		 ,@StockDateLast\r\n"
				+ "		 )  ;\r\n"
				+ " declare @CheckSameDate date  = cast ( DATEADD(month, DATEDIFF(month, 0, GETDATE()), 0  ) as DATE) ;  \r\n"
				+ "  declare @ISFirstPast int = 0 ;  \r\n"
				+ " declare @ISSecondtPast int = 0 ;  \r\n"
				+ " declare @ISThirdPast int = 0 ;  \r\n"
				+ "  \r\n"
				+ "  IF(@BeginFirstMonth <= @CheckSameDate  and @CheckSameDate  <= @LastFirstMonth)\r\n"
				+ "   \r\n"
				+ "	BEGIN\r\n"
				+ "		SET @BeginFirstMonth = CAST(GETDATE() AS DATE);\r\n"
				+ "	END \r\n"
				+ "  ELSE IF (@CheckSameDate > @BeginFirstMonth  ) \r\n"
				+ "	BEGIN\r\n"
				+ "		SET @ISFirstPast = 1;\r\n"
				+ "	END\r\n"
				+ "   IF (@BeginSecondMonth <= @CheckSameDate  and @CheckSameDate  <= @LastSecondMonth) \r\n"
				+ "	BEGIN\r\n"
				+ "		SET @BeginSecondMonth =CAST(GETDATE() AS DATE);\r\n"
				+ "	END\r\n"
				+ "  ELSE IF (@CheckSameDate > @BeginSecondMonth  ) \r\n"
				+ "	BEGIN\r\n"
				+ "		SET @ISSecondtPast = 1;\r\n"
				+ "	END\r\n"
				+ "  IF (@BeginThirdMonth <= @CheckSameDate  and @CheckSameDate  <= @LastThirdMonth) \r\n"
				+ "	BEGIN\r\n"
				+ "		SET @BeginThirdMonth = CAST(GETDATE() AS DATE);\r\n"
				+ "	END\r\n"
				+ "  ELSE IF (@CheckSameDate > @BeginThirdMonth  ) \r\n"
				+ "	BEGIN\r\n"
				+ "		SET @ISThirdPast = 1;\r\n"
				+ "	END\r\n"
				+ "	--select @BeginFirstMonth,@LastFirstMonth,@BeginSecondMonth,@LastSecondMonth,@BeginThirdMonth,@LastThirdMonth\r\n"
				+ " IF OBJECT_ID('tempdb..#tempOnprocessLotFirst') IS NOT NULL \r\n"
				+ "	 DROP TABLE #tempOnprocessLotFirst;  \r\n"
				+ " select * \r\n"
				+ " into #tempOnprocessLotFirst \r\n"
				+ " from [PPMM].[dbo].[viewTEMPPlanningLotOnProcess] as a\r\n"
				+ " where PlanUserDate >= @BeginFirstMonth and PlanUserDate <= @LastFirstMonth and\r\n"
				+ "	  LEFT(a.ProductionOrder, 1) <> 'F'   and\r\n"
				+ "	  a.[GroupNo] is not null \r\n"
				+ " IF OBJECT_ID('tempdb..#tempOnprocessLotSecond') IS NOT NULL \r\n"
				+ "	 DROP TABLE #tempOnprocessLotSecond;  \r\n"
				+ " select * \r\n"
				+ " into #tempOnprocessLotSecond \r\n"
				+ " from [PPMM].[dbo].[viewTEMPPlanningLotOnProcess] as a\r\n"
				+ " where PlanUserDate >= @BeginSecondMonth and PlanUserDate <= @LastSecondMonth and\r\n"
				+ "	  	  LEFT(a.ProductionOrder, 1) <> 'F'   and\r\n"
				+ "	 	  a.[GroupNo] is not null \r\n"
				+ " IF OBJECT_ID('tempdb..#tempOnprocessLotThird') IS NOT NULL \r\n"
				+ "	 DROP TABLE #tempOnprocessLotThird;  \r\n"
				+ " select * \r\n"
				+ " into #tempOnprocessLotThird \r\n"
				+ " from [PPMM].[dbo].[viewTEMPPlanningLotOnProcess] as a\r\n"
				+ " where PlanUserDate >= @BeginThirdMonth and PlanUserDate <= @LastThirdMonth and\r\n"
				+ "	  	  LEFT(a.ProductionOrder, 1) <> 'F'  and\r\n"
				+ "	      a.[GroupNo] is not null \r\n"
				+ " SELECT b.[Id]\r\n"
				+ "      ,a.[GroupNo]\r\n"
				+ "	  	 ,b.[SubGroup]  \r\n"
				+ "      ,a.[LotPerDay]  \r\n" 
				+ "	, STUFF((\r\n"
				+ "		SELECT ' ,' +MachineName\r\n"
				+ "		FROM [PPMM].[dbo].[InputMachineDetail] as c\r\n"
				+ "		WHERE b.GroupNo = c.GroupNo and \r\n"
				+ "			b.SubGroup = c.SubGroup and \r\n"
				+ "			c.DataStatus = 'O' and \r\n"
				+ "			MachineName <> '' \r\n"
				+ "		FOR XML PATH('')\r\n"
				+ "		), 1, 2, '') as [MachineName] \r\n"
				+ "		,CountMachine\r\n"
				+ "		,CountFirstRedye\r\n"
				+ "		,SumFirstRedyeQty\r\n"
				+ "		,CountFirstPO \r\n"
				+ "		,SumFirstPOQty    \r\n"
				+ "		,CountFirstPOAdd\r\n"
				+ "		,SumFirstPOAddQty\r\n"
				+ "		,ISNULL(CountFirstRedye,0)+ISNULL(CountFirstPO,0)+ISNULL(CountFirstPOAdd,0) AS TotalCountFirst\r\n"
				+ "		,ISNULL(SumFirstRedyeQty,0)+ISNULL(SumFirstPOQty,0)+ISNULL(SumFirstPOAddQty,0) AS TotalSumFirst\r\n"
				+ "		,CountSecondRedye\r\n"
				+ "		,SumSecondRedyeQty\r\n"
				+ "		,CountSecondPO \r\n"
				+ "		,SumSecondPOQty    \r\n"
				+ "		,CountSecondPOAdd\r\n"
				+ "		,SumSecondPOAddQty\r\n"
				+ "		,ISNULL(CountSecondRedye,0)+ISNULL(CountSecondPO,0)+ISNULL(CountSecondPOAdd,0) AS TotalCountSecond\r\n"
				+ "		,ISNULL(SumSecondRedyeQty,0)+ISNULL(SumSecondPOQty,0)+ISNULL(SumSecondPOAddQty,0) AS TotalSumSecond\r\n"
				+ "		,CountThirdRedye\r\n"
				+ "		,SumThirdRedyeQty\r\n"
				+ "		,CountThirdPO \r\n"
				+ "		,SumThirdPOQty    \r\n"
				+ "		,CountThirdPOAdd\r\n"
				+ "		,SumThirdPOAddQty\r\n"
				+ "		,ISNULL(CountThirdRedye,0)+ISNULL(CountThirdPO,0)+ISNULL(CountThirdPOAdd,0) AS TotalCountThird\r\n"
				+ "		,ISNULL(SumThirdRedyeQty,0)+ISNULL(SumThirdPOQty,0)+ISNULL(SumThirdPOAddQty,0) AS TotalSumThird\r\n"
				+ "     ,CAST( @BeginFirstMonth AS VARCHAR )	+' - '+CAST(@LastFirstMonth AS VARCHAR) as FirstMonth\r\n"
				+ "		,CAST( @BeginSecondMonth AS VARCHAR)+' - '+CAST( @LastSecondMonth AS VARCHAR) as SecondMonth\r\n"
				+ "	 	,CAST( @BeginThirdMonth AS VARCHAR)+' - '+CAST( @LastThirdMonth AS VARCHAR) as ThirdMonth\r\n"
				+ "  FROM [PPMM].[dbo].[InputMainGroupDetail] as a \r\n"
				+ "  inner join [PPMM].[dbo].[InputSubGroupDeail] as b on a.[GroupNo] = b.[GroupNo] \r\n"
				+ "  inner join ( \r\n"
				+ "		select [GroupNo],[SubGroup],count(MachineName) AS CountMachine\r\n"
				+ "		from [PPMM].[dbo].[InputMachineDetail]\r\n"
				+ "		GROUP BY [GroupNo],[SubGroup]\r\n"
				+ "  ) as c on c.[GroupNo] = b.[GroupNo] and c.[SubGroup] = b.[SubGroup]\r\n"
				+ "  LEFT JOIN (\r\n"
				+ "	  select \r\n"
				+ "		GroupNo\r\n"
				+ "		,SubGroup\r\n"
				+ "		,count(ReDyeId) as CountFirstRedye  \r\n"
				+ "		,count(TempProdId) as CountFirstPO \r\n"
				+ "		,count(TempPOAddId) as CountFirstPOAdd \r\n"
				+ "	from #tempOnprocessLotFirst \r\n"
				+ "	group by GroupNo,SubGroup \r\n"
				+ "  ) AS FIRSTCOUNT ON A.[GroupNo] = FIRSTCOUNT.[GroupNo] AND B.[SubGroup] = FIRSTCOUNT.[SubGroup]\r\n"
				+ "  LEFT JOIN (\r\n"
				+ "		select \r\n"
				+ "			GroupNo\r\n"
				+ "			,SubGroup\r\n"
				+ "			,count(ReDyeId) as CountSecondRedye  \r\n"
				+ "			,count(TempProdId) as CountSecondPO  \r\n"
				+ "			,count(TempPOAddId) as CountSecondPOAdd \r\n"
				+ "		from #tempOnprocessLotSecond\r\n"
				+ "		group by GroupNo,SubGroup\r\n"
				+ "  ) AS SECONDCOUNT ON A.[GroupNo] = SECONDCOUNT.[GroupNo] AND B.[SubGroup] = SECONDCOUNT.[SubGroup]\r\n"
				+ "  LEFT JOIN (\r\n"
				+ "	  select \r\n"
				+ "		GroupNo\r\n"
				+ "		,SubGroup\r\n"
				+ "		,count(ReDyeId) as CountThirdRedye  \r\n"
				+ "		,count(TempProdId) as CountThirdPO \r\n"
				+ "		,count(TempPOAddId) as CountThirdPOAdd \r\n"
				+ "	from #tempOnprocessLotThird \r\n"
				+ "	group by GroupNo,SubGroup \r\n"
				+ "  ) AS THIRDCOUNT ON A.[GroupNo] = THIRDCOUNT.[GroupNo] AND B.[SubGroup] = THIRDCOUNT.[SubGroup]\r\n"
				+ "  LEFT JOIN (\r\n"
				+ "  select \r\n"
				+ "	GroupNo\r\n"
				+ "	,SubGroup\r\n"
				+ "	, sum(a.[ProdOrderQty]) as SumFirstRedyeQty  \r\n"
				+ "from #tempOnprocessLotFirst as a \r\n"
				+ "WHERE ReDyeId IS NOT NULL\r\n"
				+ "group by GroupNo,SubGroup  \r\n"
				+ "  ) AS FIRSTSUMREDYE ON A.[GroupNo] = FIRSTSUMREDYE.[GroupNo] AND B.[SubGroup] = FIRSTSUMREDYE.[SubGroup]\r\n"
				+ "  LEFT JOIN (\r\n"
				+ "select \r\n"
				+ "	GroupNo\r\n"
				+ "	,SubGroup\r\n"
				+ "	, sum(a.[ProdOrderQty]) as SumFirstPOQty  \r\n"
				+ "from #tempOnprocessLotFirst as a \r\n"
				+ "WHERE A.TempProdId IS NOT NULL\r\n"
				+ "group by GroupNo,SubGroup  \r\n"
				+ "  ) AS FIRSTSUMPO ON A.[GroupNo] = FIRSTSUMPO.[GroupNo] AND B.[SubGroup] = FIRSTSUMPO.[SubGroup]\r\n"
				+ "  LEFT JOIN (\r\n"
				+ "select \r\n"
				+ "	GroupNo\r\n"
				+ "	,SubGroup\r\n"
				+ "	, sum(a.[ProdOrderQty]) as SumFirstPOAddQty  \r\n"
				+ "from #tempOnprocessLotFirst as a \r\n"
				+ "WHERE A.TempPOAddId IS NOT NULL\r\n"
				+ "group by GroupNo,SubGroup  \r\n"
				+ "  ) AS FIRSTSUMPOADD ON A.[GroupNo] = FIRSTSUMPOADD.[GroupNo] AND B.[SubGroup] = FIRSTSUMPOADD.[SubGroup]\r\n"
				+ "  LEFT JOIN (\r\n"
				+ "select \r\n"
				+ "	GroupNo\r\n"
				+ "	,SubGroup\r\n"
				+ "	, sum(a.[ProdOrderQty]) as SumSecondRedyeQty  \r\n"
				+ "from #tempOnprocessLotSecond as a \r\n"
				+ "WHERE ReDyeId IS NOT NULL\r\n"
				+ "group by GroupNo,SubGroup  \r\n"
				+ "  ) AS SecondSUMREDYE ON A.[GroupNo] = SecondSUMREDYE.[GroupNo] AND B.[SubGroup] = SecondSUMREDYE.[SubGroup]\r\n"
				+ "  LEFT JOIN (\r\n"
				+ "select \r\n"
				+ "	GroupNo\r\n"
				+ "	,SubGroup\r\n"
				+ "	, sum(a.[ProdOrderQty]) as SumSecondPOQty  \r\n"
				+ "from #tempOnprocessLotSecond as a \r\n"
				+ "WHERE A.TempProdId IS NOT NULL\r\n"
				+ "group by GroupNo,SubGroup  \r\n"
				+ "  ) AS SecondSUMPO ON A.[GroupNo] = SecondSUMPO.[GroupNo] AND B.[SubGroup] = SecondSUMPO.[SubGroup]\r\n"
				+ "  LEFT JOIN (\r\n"
				+ "select \r\n"
				+ "	GroupNo\r\n"
				+ "	,SubGroup\r\n"
				+ "	, sum(a.[ProdOrderQty]) as SumSecondPOAddQty  \r\n"
				+ "from #tempOnprocessLotSecond as a \r\n"
				+ "WHERE A.TempPOAddId IS NOT NULL\r\n"
				+ "group by GroupNo,SubGroup   \r\n"
				+ "  ) AS SecondSUMPOADD ON A.[GroupNo] = SecondSUMPOADD.[GroupNo] AND B.[SubGroup] = SecondSUMPOADD.[SubGroup]\r\n"
				+ "  LEFT JOIN (\r\n"
				+ "select \r\n"
				+ "	GroupNo\r\n"
				+ "	,SubGroup\r\n"
				+ "	, sum(a.[ProdOrderQty]) as SumThirdRedyeQty  \r\n"
				+ "from #tempOnprocessLotThird as a \r\n"
				+ "WHERE ReDyeId IS NOT NULL\r\n"
				+ "group by GroupNo,SubGroup  \r\n"
				+ "  ) AS ThirdSUMREDYE ON A.[GroupNo] = ThirdSUMREDYE.[GroupNo] AND B.[SubGroup] = ThirdSUMREDYE.[SubGroup]\r\n"
				+ "  LEFT JOIN (\r\n"
				+ "select \r\n"
				+ "	GroupNo\r\n"
				+ "	,SubGroup\r\n"
				+ "	, sum(a.[ProdOrderQty]) as SumThirdPOQty  \r\n"
				+ "from #tempOnprocessLotThird as a \r\n"
				+ "WHERE A.TempProdId IS NOT NULL\r\n"
				+ "group by GroupNo,SubGroup  \r\n"
				+ "  ) AS ThirdSUMPO ON A.[GroupNo] = ThirdSUMPO.[GroupNo] AND B.[SubGroup] = ThirdSUMPO.[SubGroup]\r\n"
				+ "  LEFT JOIN (\r\n"
				+ "select \r\n"
				+ "	GroupNo\r\n"
				+ "	,SubGroup\r\n"
				+ "	, sum(a.[ProdOrderQty]) as SumThirdPOAddQty  \r\n"
				+ "from #tempOnprocessLotThird as a \r\n"
				+ "WHERE A.TempPOAddId IS NOT NULL\r\n"
				+ "group by GroupNo,SubGroup  \r\n"
				+ "  ) AS ThirdSUMPOADD ON A.[GroupNo] = ThirdSUMPOADD.[GroupNo] AND B.[SubGroup] = ThirdSUMPOADD.[SubGroup]\r\n"
				+ " where b.[LotPerDay] > 0 \r\n"
				+ "	  \r\n"
				+ "  ORDER BY A.GroupNo , B.SubGroup ";
//		System.out.println(sql);	
		List<Map<String, Object>> datas = this.database.queryList(sql);
		list = new ArrayList<>();
		for (Map<String, Object> map : datas) {
			list.add(this.bcModel._genSummaryOSReportDetail(map));
		}
		return list;
	}

}
