package th.co.wacoal.atech.pcms2.service;

/**
 * SELECT column blocks ของ grid Main (PCMSMainDaoImpl) และ grid Detail (PCMSDetailDaoImpl)
 * รวมไว้ที่เดียวเพื่อให้เทียบกันได้ง่าย
 *
 * สำคัญ: ชื่อ field เดิมใน 2 DAO เหมือนกัน แต่ชุดคอลัมน์ต่างกันจริงโดย design
 * (คนละ grid คนละ bean — Main ใช้ SaleFullName/DesignFG/ArticleFG, Detail ใช้ Division/CustomerShortName ฯลฯ)
 * ห้าม merge MAIN_GRID_* กับ DETAIL_GRID_* เข้าด้วยกัน — column mismatch = ข้อมูลเพี้ยน
 */
public final class PCMSSelectColumns {

	private PCMSSelectColumns() {}

	// ค่าเดียวกับที่ DAO เดิมอ้างผ่าน pss.passFilterExpr (PCMSSqlService stateless)
	private static final String PASS_FILTER_EXPR = new PCMSSqlService().passFilterExpr;

	// ---- PCMSMainDaoImpl ----

	public static final String MAIN_GRID_SELECT_SW = ""
			  + "   a.SaleOrder \r\n"
			  + "	, a.[SaleLine] \r\n"
			  + "   , a.[SaleFullName] \r\n"
			  + "   , a.DesignFG\r\n"
			  + "   , a.ArticleFG\r\n"
			  + "   , a.DistChannel\r\n"
			  + "   , a.Color\r\n"
			  + "   , a.ColorCustomer\r\n"
			  + "   , a.SaleQuantity\r\n"
			  + "   , a.RemainQuantity\r\n"
			  + "   , a.SaleUnit\r\n"
			  + "   , b.ProductionOrder\r\n"
			  + "   , b.TotalQuantity \r\n"
			  + "   , UCAL.UserStatusCal as UserStatus\r\n"
			  + "   , b.LabStatus\r\n"
			  + "   , a.DueDate\r\n"
			  + "   , g.GreigeInDate \r\n"
			  + "   , g.[DyePlan]  \r\n"
			  + "   , g.[DyeActual] \r\n"
			  + "   , g.[Dryer]	 \r\n"
			  + "   , g.[Finishing] \r\n"
			  + "   , g.[Inspectation]  \r\n"
			  + "   , g.[Prepare] \r\n"
			  + "   , g.[Preset] \r\n"
			  + "   , g.[Relax] \r\n"
			  + "   , g.[CFMDateActual]\r\n"
			  + "   , g.[CFMPlanDate] \r\n"
			  + "   , g.[LotShipping] \r\n"
			  + "   , g.[DyeStatus]  \r\n"
			  + "   , h.DeliveryDate \r\n"
			  + "   , b.LabNo\r\n"
			  + "   , a.CustomerName\r\n"
			  + "   , a.CustomerShortName\r\n"
			  + "   , a.SaleNumber\r\n"
			  + "   , a.SaleCreateDate\r\n"
			  + "   , b.PrdCreateDate\r\n"
			  + "   , a.MaterialNo\r\n"
			  + "   , a.DeliveryStatus\r\n"
			  + "   , a.SaleStatus\r\n"
			  + "   , b.[LotNo] \r\n"
			  + "   , a.ShipDate \r\n"
			  + "   , CASE \r\n"
			  + "		WHEN SCC.SendCFMCusDate IS NOT NULL and SCC.SendCFMCusDate <> ''  THEN SCC.SendCFMCusDate \r\n"
			  + "    	ELSE  g.SendCFMCusDate \r\n"
			  + "     END AS SendCFMCusDate\r\n"
			  + "   , g.PlanGreigeDate \r\n"
			  + "   , g.CFMDetailAll \r\n"
			  + "   , g.RollNoRemarkAll \r\n"
			  + "   , 'Switch' as TypePrd \r\n"
    		  + "   , a.TypePrdRemark \r\n"
	  		  + "   , a.[PurchaseOrder] \r\n";

	public static final String MAIN_GRID_SELECT_MAIN_V2 = ""
			+ "    b.SaleOrder \r\n"
			+ "	  , b.[SaleLine] \r\n"
			+ "   , b.[SaleFullName] \r\n"
			+ "   , b.DesignFG\r\n"
			+ "   , b.ArticleFG\r\n"
			+ "   , b.DistChannel\r\n"
			+ "   , b.Color\r\n"
			+ "   , b.ColorCustomer\r\n"
			+ "   , b.SaleQuantity\r\n"
			+ "   , b.RemainQuantity\r\n"
			+ "   , b.SaleUnit\r\n"
			+ "   , b.ProductionOrder\r\n"
			+ "   , b.TotalQuantity \r\n"
			+ "   ,	b.UserStatus\r\n"
			+ "   , b.LabStatus\r\n"
			+ "   , b.DueDate\r\n"
			+ "   , b.GreigeInDate \r\n"
			+ "   , b.[DyePlan]  \r\n"
			+ "   , b.[DyeActual] \r\n"
			+ "   , b.[Dryer]	 \r\n"
			+ "   , b.[Finishing] \r\n"
			+ "   , b.[Inspectation]  \r\n"
			+ "   , b.[Prepare] \r\n"
			+ "   , b.[Preset] \r\n"
			+ "   , b.[Relax] \r\n"
			+ "   , b.[CFMDateActual]\r\n"
			+ "   , b.[CFMPlanDate] \r\n"
			+ "   , b.[LotShipping] \r\n"
			+ "   , b.[DyeStatus]  \r\n"
			+ "   , b.DeliveryDate \r\n"
			+ "   , b.LabNo\r\n"
			+ "   , b.CustomerName\r\n"
			+ "   , b.CustomerShortName\r\n"
			+ "   , b.SaleNumber\r\n"
			+ "   , b.SaleCreateDate\r\n"
			+ "   , b.PrdCreateDate\r\n"
			+ "   , b.MaterialNo\r\n"
			+ "   , b.DeliveryStatus"
			+ "   , b.SaleStatus\r\n"
			+ "   , b.[LotNo] \r\n"
			+ "   , b.ShipDate \r\n"
			+ "   , b.SendCFMCusDate\r\n"
			+ "   , 'Main' as TypePrd \r\n"
			+ "   , 'Main' AS TypePrdRemark \r\n"
  		    + "   , b.[PurchaseOrder] \r\n"
  		    + "   , b.PlanGreigeDate\r\n"
  		    + "   , b.CFMDetailAll \r\n"
  		    + "   , b.RollNoRemarkAll \r\n";

	public static final String MAIN_GRID_SELECT_ALL = ""
			  + "  a.SaleOrder \r\n"
			  + ", a.[SaleLine] \r\n"
			  + ", a.[SaleFullName]   \r\n"
			  + ", a.DesignFG\r\n"
			  + ", a.ArticleFG\r\n"
			  + ", a.DistChannel\r\n"
			  + ", a.Color\r\n"
			  + ", a.ColorCustomer\r\n"
			  + ", a.SaleQuantity\r\n"
			  + ", a.RemainQuantity\r\n"
			  + ", a.SaleUnit\r\n"
			  + ", a.ProductionOrder\r\n"
			  + ", a.TotalQuantity \r\n"
			  + ", a.UserStatus\r\n"
			  + ", a.LabStatus\r\n"
			  + ", a.DueDate\r\n"
			  + ", a.GreigeInDate \r\n"
			  + ", a.[DyePlan]  \r\n"
			  + ", a.[DyeActual] \r\n"
			  + ", a.[Dryer]	 \r\n"
			  + ", a.[Finishing] \r\n"
			  + ", a.[Inspectation]  \r\n"
			  + ", a.[Prepare] \r\n"
			  + ", a.[Preset] \r\n"
			  + ", a.[Relax] \r\n"
			  + ", a.[CFMDateActual]\r\n"
			  + ", a.[CFMPlanDate] \r\n"
			  + ", a.[LotShipping] \r\n"
			  + ", a.[DyeStatus]  \r\n"
			  + ", a.DeliveryDate \r\n"
			  + ", a.LabNo\r\n"
			  + ", a.CustomerName\r\n"
			  + ", a.CustomerShortName\r\n"
			  + ", a.SaleNumber\r\n"
			  + ", a.SaleCreateDate\r\n"
			  + ", a.PrdCreateDate\r\n"
			  + ", a.MaterialNo\r\n"
			  + ", a.DeliveryStatus   \r\n"
			  + ", a.SaleStatus\r\n"
			  + ", a.[LotNo] \r\n"
			  + ", a.ShipDate \r\n"
			  + ", a.SendCFMCusDate\r\n"
			  + ", a.TypePrd \r\n"
			  + ", a.TypePrdRemark \r\n"
			  + ", a.[PurchaseOrder]     \r\n"
  		      + ", a.[PlanGreigeDate]\r\n"
  		      + ", a.CFMDetailAll \r\n"
  		      + ", a.RollNoRemarkAll \r\n";

	public static final String MAIN_GRID_LEFT_JOIN_BSELECT = ""
	 		  + "			      a.[BillSendQuantity]\r\n"
	 		  + "                ,a.[SaleOrder]\r\n"
	 		  + "                ,a.[Saleline]\r\n"
	 		  + "                ,a.[TotalQuantity]\r\n"
	 		  + "                ,a.[Unit]\r\n"
	 		  + "                ,a.[RemAfterCloseOne]\r\n"
	 		  + "                ,a.[RemAfterCloseTwo]\r\n"
	 		  + "                ,a.[RemAfterCloseThree]\r\n"
	 		  + "                ,a.[LabStatus]\r\n"
	 		  + "                ,a.[DesignFG]\r\n"
	 		  + "                ,a.[ArticleFG]\r\n"
	 		  + "                ,a.[BookNo]\r\n"
	 		  + "                ,a.[Center]\r\n"
	 		  + "                ,a.[Batch]\r\n"
	 		  + "                ,a.[LabNo]\r\n"
	 		  + "                ,a.[RemarkOne]\r\n"
	 		  + "                ,a.[RemarkTwo]\r\n"
	 		  + "                ,a.[RemarkThree]\r\n"
	 		  + "                ,a.[BCAware]\r\n"
	 		  + "                ,a.[OrderPuang]\r\n"
	 		  + "                ,a.[RefPrd]\r\n"
	 		  + "                ,a.[GreigeInDate]\r\n"
	 		  + "                ,a.[BCDate]\r\n"
	 		  + "                ,a.[Volumn]\r\n"
	 		  + "                ,a.[CFdate]\r\n"
	 		  + "                ,a.[CFType]\r\n"
	 		  + "                ,a.[Shade]\r\n"
	 		  + "                ,g.[LotShipping]\r\n"
	 		  + "                ,m.[Grade]\r\n"
	 		  + "                ,a.[PrdCreateDate]\r\n"
	 		  + "                ,a.[GreigeArticle]\r\n"
	 		  + "                ,a.[GreigeDesign]\r\n"
	 		  + "                ,a.[GreigeMR]\r\n"
	 		  + "                ,a.[GreigeKG]\r\n"
	 		  + "                ,a.[ProductionOrder]\r\n"
	 		  + "                ,a.[LotNo]\r\n"
			  + "			     , adjVol AS SumVol\r\n"
			  + "				 , a.Price * adjVol AS SumVolFGAmount"
	 		  + "                ,a.Volumn           as RealVolumn\r\n"
	 		  + "                ,g.[DyePlan]\r\n"
	 		  + "                ,g.[DyeActual]\r\n"
	 		  + "                ,g.[Dryer]\r\n"
	 		  + "                ,g.[Finishing]\r\n"
	 		  + "                ,g.[Inspectation]\r\n"
	 		  + "                ,g.[Prepare]\r\n"
	 		  + "                ,g.[Preset]\r\n"
	 		  + "                ,g.[Relax]\r\n"
	 		  + "                ,g.[CFMDateActual]\r\n"
	 		  + "                ,g.[CFMPlanDate]\r\n"
	 		  + "                ,g.[DyeStatus]\r\n"
	 		  + "                ,h.DeliveryDate\r\n"
	 		  + "                ,UCAL.UserStatusCal as UserStatus\r\n"
	 		  + "                ,coalesce ( SCC.SendCFMCusDate ,g.SendCFMCusDate ) AS SendCFMCusDate \r\n"
	 		  + "                ,m.GRSumKG\r\n"
	 		  + "                ,m.GRSumYD\r\n"
	 		  + "                ,m.GRSumMR\r\n"
	 		  + "                ,g.PlanGreigeDate\r\n"
	 		  + "                ,g.CFMDetailAll\r\n"
	 		  + "                ,g.RollNoRemarkAll\r\n"
	 		  + "                ,a.Division\r\n"
	 		  + "                ,a.CustomerShortName\r\n"
	 		  + "                ,a.SaleCreateDate\r\n"
	 		  + "                ,a.PurchaseOrder\r\n"
	 		  + "                ,a.MaterialNo\r\n"
	 		  + "                ,a.CustomerMaterial\r\n"
	 		  + "                ,a.CustomerMaterialBase\r\n"
	 		  + "                ,a.Price\r\n"
	 		  + "                ,a.SaleUnit\r\n"
	 		  + "                ,a.OrderAmount\r\n"
	 		  + "                ,a.SaleQuantity\r\n"
	 		  + "                ,a.RemainQuantity\r\n"
	 		  + "                ,a.RemainAmount\r\n"
	 		  + "                ,a.CustomerDue\r\n"
	 		  + "                ,a.DueDate\r\n"
	 		  + "                ,a.ShipDate\r\n"
	 		  + "                ,a.[SaleNumber]\r\n"
	 		  + "                ,a.[SaleFullName]\r\n"
	 		  + "                ,a.DistChannel\r\n"
	 		  + "                ,a.Color\r\n"
	 		  + "                ,a.ColorCustomer\r\n"
	 		  + "                ,a.CustomerName\r\n"
	 		  + "                ,a.DeliveryStatus\r\n"
	 		  + "                ,a.SaleStatus\r\n"
	 		  + PASS_FILTER_EXPR;

	// ---- PCMSDetailDaoImpl ----

	public static final String DETAIL_GRID_SELECT_SW = ""
			+ "   a.SaleOrder, \r\n"
			+ "	  a.[SaleLine], \r\n"
			+ "   a.Division,\r\n"
			+ "   a.CustomerShortName,	\r\n"
			+ "   a.SaleCreateDate,\r\n"
			+ "   a.PurchaseOrder,\r\n"
			+ "   a.MaterialNo,\r\n"
			+ "   a.CustomerMaterial,\r\n"
			+ "   a.Price,\r\n"
			+ "   a.SaleUnit,\r\n"
			+ "   a.OrderAmount,\r\n"
			+ "   a.SaleQuantity,\r\n"
			+ "   a.RemainQuantity,\r\n"
			+ "   a.RemainAmount,\r\n"
			+ "   b.TotalQuantity,\r\n"
			+ "   m.Grade,\r\n"
			+ "   FSMBB.BillSendWeightQuantity,\r\n"
			+ "   case\r\n"
			+ "		 WHEN a.SaleUnit  = 'KG' THEN FSMBB.BillSendWeightQuantity   \r\n"
			+ "		 WHEN a.SaleUnit  = 'YD' THEN FSMBB.BillSendYDQuantity  \r\n"
			+ "		 ELSE FSMBB.BillSendMRQuantity\r\n"
			+ "	  end AS BillSendQuantity ,\r\n"
			+ "   FSMBB.BillSendMRQuantity,\r\n"
			+ "   FSMBB.BillSendYDQuantity,\r\n"
			+ "   a.CustomerDue,\r\n"
			+ "   a.DueDate,\r\n"
			+ "   b.ProductionOrder,\r\n"
			+ "   b.LotNo,\r\n"
			+ "   b.LabNo,\r\n"
			+ "   b.LabStatus,\r\n"
			+ "   CAST(NULL AS date) AS CFMPlanLabDate,\r\n"
			+ "   g.CFMActualLabDate,\r\n"
			+ "   g.CFMCusAnsLabDate,\r\n"
			+ "   UCAL.UserStatusCal as UserStatus,\r\n"
			+ "   CAST(NULL AS date) AS TKCFM, \r\n"
			+ "   g.CFMPlanDate AS CFMPlanDate ,  \r\n"
			+ "   coalesce ( SCC.SendCFMCusDate ,g.SendCFMCusDate ) AS SendCFMCusDate, \r\n"
			+ "   CASE \r\n"
			+ "		WHEN h.[ProductionOrder] is not null \r\n"
			+ "		THEN H.DeliveryDate ELSE b.CFTYPE \r\n"
			+ "		END AS DeliveryDate , \r\n"
			+ "   CFMDateActual,\r\n"
			+ "   g.CFMDetailAll, \r\n"
			+ "   g.CFMNumberAll,  \r\n"
			+ "   g.CFMRemarkAll, \r\n"
			+ "   g.RollNoRemarkAll , \r\n"
			+ "   a.ShipDate,\r\n"
			+ "   b.RemarkOne,\r\n"
			+ "   b.RemarkTwo,\r\n"
			+ "   b.RemarkThree ,\r\n"
			+ "   CAST(NULL AS NVARCHAR(MAX)) AS ReplacedRemark ,\r\n"
			+ "   CAST(NULL AS NVARCHAR(MAX)) AS StockRemark,\r\n"
			+ "   m.GRSumKG,\r\n"
			+ "   m.GRSumYD,\r\n"
			+ "   m.GRSumMR,\r\n"
			+ "   g.DyePlan , \r\n"
			+ "   g.DyeActual, \r\n"
			+ "   CAST(NULL AS NVARCHAR(MAX)) AS PCRemark, \r\n"
			+ "   CAST(NULL AS NVARCHAR(MAX)) AS [DelayedDep], \r\n"
			+ "   CAST(NULL AS NVARCHAR(MAX)) AS [CauseOfDelay], \r\n"
			+ "   CAST(NULL AS NVARCHAR(MAX)) AS [SwitchRemark],\r\n"
			+ "   CAST(NULL AS NVARCHAR(MAX)) AS [StockLoad], \r\n"
			+ "   b.[PrdCreateDate],\r\n"
			+ "   g.LotShipping,\r\n"
			+ "   g.PlanGreigeDate\r\n ";

	public static final String DETAIL_GRID_SELECT_MAIN_V2 = ""
			+ "   b.SaleOrder, \r\n"
			+ "   b.[SaleLine], \r\n"
			+ "   b.Division,\r\n"
			+ "   b.CustomerShortName,\r\n"
			+ "   b.SaleCreateDate,\r\n"
			+ "   b.PurchaseOrder,\r\n"
			+ "   b.MaterialNo,\r\n"
			+ "   b.CustomerMaterial,\r\n"
			+ "   b.Price,\r\n"
			+ "   b.SaleUnit,\r\n"
			+ "   b.OrderAmount,\r\n"
			+ "   b.SaleQuantity,\r\n"
			+ "   b.RemainQuantity,\r\n"
			+ "   b.RemainAmount,\r\n"
			+ "   b.TotalQuantity,\r\n"
			+ "   b.Grade,\r\n"
			+ "   b.BillSendWeightQuantity,\r\n"
			+ "   b.BillSendQuantity,\r\n"
			+ "   b.BillSendMRQuantity,\r\n"
			+ "   b.BillSendYDQuantity,\r\n"
			+ "   b.CustomerDue,\r\n"
			+ "   b.DueDate,\r\n"
			+ "   b.ProductionOrder,\r\n"
			+ "   b.LotNo,\r\n"
			+ "   b.LabNo,\r\n"
			+ "   b.LabStatus,\r\n"
			+ "   CAST(NULL AS date) AS CFMPlanLabDate,\r\n"
			+ "   b.CFMActualLabDate,\r\n"
			+ "   b.CFMCusAnsLabDate,\r\n"
			+ "   b.UserStatus,\r\n"
			+ "   CAST(NULL AS date) AS TKCFM, \r\n"
			+ "   b.CFMPlanDate AS CFMPlanDate ,  \r\n"
			+ "   b.SendCFMCusDate,\r\n"
			+ "   CASE \r\n"
			+ "		WHEN b.[ProductionOrder] is not null THEN b.DeliveryDate \r\n"
			+ "		ELSE b.CFTYPE \r\n"
			+ "		END AS DeliveryDate , \r\n"
			+ "   b.CFMDateActual,\r\n"
			+ "   b.CFMDetailAll,\r\n"
			+ "   b.CFMNumberAll,\r\n"
			+ "   b.CFMRemarkAll,\r\n"
			+ "   b.RollNoRemarkAll , \r\n"
			+ "   b.ShipDate,\r\n"
			+ "   b.RemarkOne,\r\n"
			+ "   b.RemarkTwo,\r\n"
			+ "   b.RemarkThree ,\r\n"
			+ "   CAST(NULL AS NVARCHAR(MAX)) AS ReplacedRemark ,\r\n"
			+ "   CAST(NULL AS NVARCHAR(MAX)) AS StockRemark,\r\n"
			+ "   b.GRSumKG,\r\n"
			+ "   b.GRSumYD,\r\n"
			+ "   b.GRSumMR,\r\n"
			+ "   b.DyePlan , \r\n"
			+ "   b.DyeActual, \r\n"
			+ "   CAST(NULL AS NVARCHAR(MAX)) AS PCRemark,\r\n"
			+ "   CAST(NULL AS NVARCHAR(MAX)) AS [DelayedDep],\r\n"
			+ "   CAST(NULL AS NVARCHAR(MAX)) AS [CauseOfDelay],\r\n"
			+ "   CAST(NULL AS NVARCHAR(MAX)) AS [SwitchRemark],\r\n"
			+ "   CAST(NULL AS NVARCHAR(MAX)) AS [StockLoad],\r\n"
			+ "   b.[PrdCreateDate], \r\n"
			+ "   b.LotShipping\r\n";

	public static final String DETAIL_GRID_SELECT_ALL = ""
			+ "   a.SaleOrder,\r\n"
			+ "   a.[SaleLine] ,\r\n"
			+ "   a.Division,\r\n"
			+ "   a.CustomerShortName,	 \r\n"
			+ "   a.SaleCreateDate,\r\n"
			+ "   a.PurchaseOrder,\r\n"
			+ "   a.MaterialNo,\r\n"
			+ "   a.CustomerMaterial,\r\n"
			+ "   a.Price,\r\n"
			+ "   a.SaleUnit,\r\n"
			+ "   a.OrderAmount,\r\n"
			+ "   a.SaleQuantity,\r\n"
			+ "   a.RemainQuantity,\r\n"
			+ "   a.RemainAmount,\r\n"
			+ "   a.TotalQuantity,\r\n"
			+ "   a.Grade,\r\n"
			+ "   a.BillSendWeightQuantity, \r\n"
			+ "   a.BillSendQuantity, \r\n"
			+ "   a.BillSendMRQuantity,\r\n"
			+ "   a.BillSendYDQuantity, \r\n"
			+ "   a.CustomerDue,\r\n"
			+ "   a.DueDate,\r\n"
			+ "   a.ProductionOrder,\r\n"
			+ "   a.LotNo,\r\n"
			+ "   a.LabNo,\r\n"
			+ "   a.LabStatus,\r\n"
			+ "   a.CFMPlanLabDate,\r\n"
			+ "   a.CFMActualLabDate,\r\n"
			+ "   a.CFMCusAnsLabDate,\r\n"
			+ "   a.UserStatus,\r\n"
			+ "   a.TKCFM,\r\n"
			+ "   a.CFMPlanDate ,  \r\n"
			+ "   a.SendCFMCusDate,\r\n"
			+ "   a.DeliveryDate , \r\n"
			+ "   a.CFMDateActual,\r\n"
			+ "   a.CFMDetailAll, \r\n"
			+ "   a.CFMNumberAll,  \r\n"
			+ "   a.CFMRemarkAll, \r\n"
			+ "   a.RollNoRemarkAll , \r\n"
			+ "   a.ShipDate,\r\n"
			+ "   a.RemarkOne,\r\n"
			+ "   a.RemarkTwo,\r\n"
			+ "   a.RemarkThree ,\r\n"
			+ "   a.ReplacedRemark ,\r\n"
			+ "   a.StockRemark,\r\n"
			+ "   a.GRSumKG,\r\n"
			+ "   a.GRSumYD,\r\n"
			+ "   a.GRSumMR,\r\n"
			+ "   a.DyePlan, \r\n"
			+ "   a.DyeActual, \r\n"
			+ "   a.PCRemark,\r\n"
			+ "   a.[DelayedDep],\r\n"
			+ "   a.[CauseOfDelay],\r\n"
			+ "   a.[SwitchRemark],\r\n"
			+ "   a.[StockLoad],\r\n"
			+ "   a.[PrdCreateDate]\r\n"
			+ "   , a.LotShipping\r\n"
			+ "   , a.Volumn  \r\n"
			+ "   , a.VolumnFGAmount \r\n"
			+ "   , a.TypePrd \r\n"
			+ "   , a.TypePrdRemark \r\n"
			+ "   , a.[DyeStatus]\r\n"
			+ "   , a.[CustomerMaterialBase]\r\n";

	public static final String DETAIL_GRID_LEFT_JOIN_BSELECT = ""
			+ "                 a.[SaleOrder]\r\n"
			+ "                ,a.[Saleline]\r\n"
			+ "                ,a.[TotalQuantity]\r\n"
			+ "                ,a.[Unit]\r\n"
			+ "                ,a.[RemAfterCloseOne]\r\n"
			+ "                ,a.[RemAfterCloseTwo]\r\n"
			+ "                ,a.[RemAfterCloseThree]\r\n"
			+ "                ,a.[LabStatus]\r\n"
			+ "                ,a.[DesignFG]\r\n"
			+ "                ,a.[ArticleFG]\r\n"
			+ "                ,a.[BookNo]\r\n"
			+ "                ,a.[Center]\r\n"
			+ "                ,a.[Batch]\r\n"
			+ "                ,a.[LabNo]\r\n"
			+ "                ,a.[RemarkOne]\r\n"
			+ "                ,a.[RemarkTwo]\r\n"
			+ "                ,a.[RemarkThree]\r\n"
			+ "                ,a.[BCAware]\r\n"
			+ "                ,a.[OrderPuang]\r\n"
			+ "                ,a.[RefPrd]\r\n"
			+ "                ,a.[GreigeInDate]\r\n"
			+ "                ,a.[BCDate]\r\n"
			+ "                ,a.[Volumn]\r\n"
			+ "                ,a.[CFdate]\r\n"
			+ "                ,a.[CFType]\r\n"
			+ "                ,a.[Shade]\r\n"
			+ "                ,g.[LotShipping]\r\n"
			+ "                ,m.[Grade]\r\n"
			+ "                ,a.[PrdCreateDate]\r\n"
			+ "                ,a.[GreigeArticle]\r\n"
			+ "                ,a.[GreigeDesign]\r\n"
			+ "                ,a.[GreigeMR]\r\n"
			+ "                ,a.[GreigeKG]\r\n"
			+ "                ,a.[ProductionOrder]\r\n"
			+ "                ,a.[LotNo]\r\n\r\n"
			+ "			       , adjVol AS SumVol\r\n"
			+ "				   , a.Price * adjVol AS SumVolFGAmount"
			+ "                ,a.Volumn as RealVolumn\r\n"
			+ "                ,g.[DyePlan]\r\n"
			+ "                ,g.[DyeActual]\r\n"
			+ "                ,g.[Dryer]\r\n"
			+ "                ,g.[Finishing]\r\n"
			+ "                ,g.[Inspectation]\r\n"
			+ "                ,g.[Prepare]\r\n"
			+ "                ,g.[Preset]\r\n"
			+ "                ,g.[Relax]\r\n"
			+ "                ,g.[CFMDateActual]\r\n"
			+ "                ,g.[CFMPlanDate]\r\n"
			+ "                ,g.[DyeStatus]\r\n"
			+ "                ,h.DeliveryDate\r\n"
			+ "                ,UCAL.UserStatusCal as UserStatus\r\n"
			+ "  			   ,coalesce ( SCC.SendCFMCusDate ,g.SendCFMCusDate ) AS SendCFMCusDate \r\n"
			+ "                ,GRSumKG\r\n"
			+ "                ,GRSumYD\r\n"
			+ "                ,GRSumMR\r\n"
			+ "                ,g.CFMDetailAll\r\n"
			+ "                ,g.CFMNumberAll\r\n"
			+ "                ,g.CFMRemarkAll\r\n"
			+ "                ,g.RollNoRemarkAll\r\n"
			+ "                ,g.CFMActualLabDate\r\n"
			+ "                ,g.CFMCusAnsLabDate\r\n"
			+ "                ,FSMBB.BillSendWeightQuantity\r\n"
			+ "                ,case\r\n"
			+ "                   WHEN a.SaleUnit = 'KG' THEN FSMBB.BillSendWeightQuantity\r\n"
			+ "                   WHEN a.SaleUnit = 'YD' THEN FSMBB.BillSendYDQuantity\r\n"
			+ "                   ELSE FSMBB.BillSendMRQuantity\r\n"
			+ "                 end                AS BillSendQuantity\r\n"
			+ "                ,FSMBB.BillSendMRQuantity\r\n"
			+ "                ,FSMBB.BillSendYDQuantity\r\n"
			+ "                ,g.PlanGreigeDate\r\n"
			+ "                ,a.Division\r\n"
			+ "                ,a.CustomerShortName\r\n"
			+ "                ,a.SaleCreateDate\r\n"
			+ "                ,a.PurchaseOrder\r\n"
			+ "                ,a.MaterialNo\r\n"
			+ "                ,a.CustomerMaterial\r\n"
			+ "                ,a.CustomerMaterialBase\r\n"
			+ "                ,a.Price\r\n"
			+ "                ,a.SaleUnit\r\n"
			+ "                ,a.OrderAmount\r\n"
			+ "                ,a.SaleQuantity\r\n"
			+ "                ,a.RemainQuantity\r\n"
			+ "                ,a.RemainAmount\r\n"
			+ "                ,a.CustomerDue\r\n"
			+ "                ,a.DueDate\r\n"
			+ "                ,a.ShipDate\r\n"
			+ "                ,a.[SaleNumber]\r\n"
			+ "                ,a.[SaleFullName]\r\n"
			+ "                ,a.DistChannel\r\n"
			+ "                ,a.Color\r\n"
			+ "                ,a.ColorCustomer\r\n"
			+ "                ,a.CustomerName\r\n"
			+ "                ,a.DeliveryStatus\r\n"
			+ "                ,a.SaleStatus\r\n"
			+ PASS_FILTER_EXPR;
}
